Repository CS2113-AY1819S1-F09-1/main, pull requests merged in 2018-10, with the labels that each got.

#26 SearchHistoryManager no longer a singleton class +Added some tests + Add undosearch command
  src/main/java/seedu/address/logic/commands/ClearSearchHistoryCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/FindPersonSubCommand.java
  src/main/java/seedu/address/logic/commands/FindTagSubCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/UndoSearchCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/SearchHistoryManager.java
  src/main/java/seedu/address/model/searchhistory/SearchHistoryManager.java
  src/main/java/seedu/address/model/searchhistory/exceptions/EmptyHistoryException.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/model/person/TagContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.enhancement, type.epic

#45 Updated DG to include relevant pictures
  docs/DeveloperGuide.adoc
  docs/images/CorrectIdPassword.PNG
  docs/images/CorrectIdWrongPassword.PNG
  docs/images/InitialLoginBookList.PNG
  docs/images/LoginException.PNG
  docs/images/ParseCorrectId.JPG
  docs/images/ParseCorrectIdList.PNG
  docs/images/WrongIdCorrectPassword.PNG
  docs/images/WrongIdOrPasswordList.PNG
  docs/images/WrongIdPassword.PNG
Labels: type.task

#44 Implemented exclude from search feature
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/FindPersonSubCommand.java
  src/main/java/seedu/address/logic/commands/FindTagSubCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: priority.high

#48 AddSkillLevel Command Implementation.
  Compilation
  docs/LearningOutcomes.adoc
  src/main/java/seedu/address/logic/commands/AddSkillCommand.java
  src/main/java/seedu/address/logic/commands/AddSkillLevelCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddSkillCommandParser.java
  src/main/java/seedu/address/logic/parser/AddSkillLevelCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Skill.java
  src/main/java/seedu/address/model/person/SkillLevel.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/XmlAddressBookStorageTest/invalidAndValidPersonAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/duplicatePersonAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
  src/test/data/XmlUtilTest/validAddressBook.xml
  src/test/java/guitests/guihandles/PersonCardHandle.java
  src/test/java/seedu/address/logic/commands/AddSkillLevelCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/ui/PersonListPanelTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
Labels: type.enhancement

#49 Updated User Guide and Developers Guide with screenshots and diagram
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/BudgetCommandSequenceDiagram.pptx
  docs/images/BudgetCommandSequenceDiagram.png
  docs/images/DuplicateBudgetCommand.PNG
  docs/images/EnterBudgetCommand.PNG
  docs/images/ExecutedBudgetCommand.PNG
Labels: priority.medium, type.task

#51 Documentation: AddSkillLevelCommand
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/aslafter.png
  docs/images/aslbefore.png
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: priority.medium, type.task

#55 edited the BudgetCommandSequenceDiagram
  docs/DeveloperGuide.adoc
  docs/diagrams/BudgetCommandSequenceDiagram.pptx
  docs/images/BudgetCommandSequenceDiagram.png
  docs/images/DuplicateBudgetCommand.PNG
  docs/images/EnterBudgetCommand.PNG
  docs/images/ExecutedBudgetCommand.PNG
Labels: severity.Low, type.task

#60 replaced SearchHistoryManager getter method with Facade Pattern in Model
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/FindPersonSubCommand.java
  src/main/java/seedu/address/logic/commands/FindTagSubCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/UndoSearchCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/TagContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/searchhistory/SearchHistoryManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
Labels: priority.high

#65 Creating Tests
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/searchhistory/SearchHistoryManager.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoSearchCommandTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/SearchHistoryManagerTest.java
  src/test/java/seedu/address/testutil/SearchHistoryManagerUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.high

#64 V1.3: ViewClubBudgetsCommand and edited BudgetCalculationCommand
  src/main/java/seedu/address/logic/arithmetic/CalculateTotalAttendees.java
  src/main/java/seedu/address/logic/commands/BudgetCalculationCommand.java
  src/main/java/seedu/address/logic/commands/ViewClubBudgetsCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ViewClubBudgetsCommandParser.java
  src/main/java/seedu/address/model/clubbudget/exceptions/DuplicateFinalClubBudgetException.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/BudgetCommandParserTest.java
  src/test/java/seedu/address/testutil/ClubBudgetElementsBuilder.java
  src/test/java/seedu/address/testutil/ClubBudgetElementsUtil.java
  src/test/java/seedu/address/testutil/TypicalClubBudgetElements.java
Labels: priority.high

#77 Skill level bugfix
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/test/data/XmlSerializableAddressBookTest/duplicatePersonAddressBook.xml
  src/test/data/XmlUtilTest/validAddressBook.xml
Labels: severity.Medium, type.bug

#81 Cleans up the UI, compresses SkillLevel and Skill into one line
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/XmlUtilTest/invalidPersonField.xml
Labels: priority.low, type.enhancement

#78 More changes to how KeywordsRecord works
  src/main/java/seedu/address/logic/commands/FindNameSubCommand.java
  src/main/java/seedu/address/logic/commands/formatter/KeywordsOutputFormatter.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/searchhistory/KeywordsBundle.java
  src/main/java/seedu/address/model/searchhistory/KeywordsHistoryStack.java
  src/main/java/seedu/address/model/searchhistory/KeywordsRecord.java
  src/main/java/seedu/address/model/searchhistory/KeywordsSet.java
  src/main/java/seedu/address/model/searchhistory/ReadOnlyKeywordsRecord.java
  src/main/java/seedu/address/model/searchhistory/SearchHistoryManager.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/SearchHistoryManagerTest.java
  src/test/java/seedu/address/model/searchhistory/KeywordsBundleTest.java
  src/test/java/seedu/address/model/searchhistory/KeywordsHistoryStackTest.java
  src/test/java/seedu/address/model/searchhistory/KeywordsRecordTest.java
  src/test/java/seedu/address/model/searchhistory/KeywordsSetTest.java
  src/test/java/seedu/address/model/searchhistory/SearchHistoryManagerTest.java
  src/test/java/seedu/address/model/searchhistory/util/SearchHistoryTestUtil.java
  src/test/java/seedu/address/testutil/SearchHistoryManagerUtil.java
Labels: priority.high

#83 Boon Jun Personal portfolio update
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/BoonJun.adoc
Labels: priority.high

#79 Created hashing of login details for greater application security, updated relevant tests and updated documentations
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/CreateAccountFailure.PNG
  docs/images/DefaultAccountDetails.PNG
  docs/images/LoginSuccess.PNG
  docs/images/RepeatLoginSequenceDiagram.png
  docs/team/MelvinTanJitChong.adoc
  src/main/java/seedu/address/logic/LoginManager.java
  src/main/java/seedu/address/logic/commands/CreateAccountCommand.java
  src/main/java/seedu/address/logic/commands/LoginUserIdPasswordRoleCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CreateAccountCommandParser.java
  src/main/java/seedu/address/logic/parser/LoginUserIdPasswordRoleCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/login/LoginDetails.java
  src/main/java/seedu/address/model/login/UserId.java
  src/main/java/seedu/address/model/login/UserPassword.java
  src/main/java/seedu/address/model/login/UserRole.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAccount.java
  src/main/java/seedu/address/storage/XmlSerializableLoginBook.java
  src/test/data/XmlLoginBookStorageTest/invalidAccountLoginBook.xml
  src/test/data/XmlLoginBookStorageTest/invalidAndValidAccountLoginBook.xml
  src/test/data/XmlSerializableLoginBookTest/invalidAccountsLoginBook.xml
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/LoginUserIdPasswordRoleCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/CreateAccountCommandParserTest.java
  src/test/java/seedu/address/logic/parser/LoginUserIdPasswordRoleCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/LoginBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/login/UniqueAccountListTest.java
  src/test/java/seedu/address/storage/XmlAccountTest.java
  src/test/java/seedu/address/storage/XmlLoginBookStorageTest.java
  src/test/java/seedu/address/storage/XmlSerializableLoginBookTest.java
  src/test/java/seedu/address/testutil/AccountBuilder.java
  src/test/java/seedu/address/testutil/AccountUtil.java
  src/test/java/seedu/address/testutil/TypicalAccounts.java
  src/test/java/systemtests/AddCommandSystemTest.java
Labels: priority.high, type.task

#85 Updating Search Pruning Feature section in user guide
  docs/UserGuide.adoc
  docs/images/SearchPruning10th.png
  docs/images/SearchPruning1st.png
  docs/images/SearchPruning2nd.png
  docs/images/SearchPruning3rd.png
  docs/images/SearchPruning4th.png
  docs/images/SearchPruning5th.png
  docs/images/SearchPruning6th.png
  docs/images/SearchPruning7th.png
  docs/images/SearchPruning8th.png
  docs/images/SearchPruning9th.png
Labels: priority.high
