Repository CS2113-AY1819S1-F09-1/main, pull requests merged in 2018-11, with the labels that each got.

#76 SkillLevel constraint
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/AddSkillCommand.java
  src/main/java/seedu/address/logic/commands/AddSkillLevelCommand.java
  src/main/java/seedu/address/model/person/SkillLevel.java
  src/test/java/seedu/address/logic/commands/AddSkillLevelCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
Labels: severity.Low, type.bug

#90 Allows swapping of \tag and \exclude option in find commands
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: priority.medium, type.enhancement

#88 Updated README.adoc
  README.adoc
  docs/images/Ui.png
Labels: type.task

#98 Updated Documentation and PPP
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/asl_sequence.png
  docs/images/aslafter.png
  docs/images/aslbefore.png
  docs/team/Jonathan.adoc
Labels: priority.high

#96 Updated SampleTestUtil to include more default accounts
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/parser/CreateAccountCommandParserTest.java
Labels: type.task

#125 Renaming of PPP files
  docs/AboutUs.adoc
  docs/images/Ui.png
  docs/team/chocological.adoc
  docs/team/derpyplops.adoc
  docs/team/ladderinc.adoc
  docs/team/sanjukta99.adoc
Labels: priority.high

#124 created new tests and changed error messages
  docs/images/longdivider.png
  docs/team/sanjukta99.adoc
  src/main/java/seedu/address/logic/commands/BudgetCalculationCommand.java
  src/main/java/seedu/address/logic/commands/BudgetCommand.java
  src/main/java/seedu/address/logic/commands/ViewClubBudgetsCommand.java
  src/main/java/seedu/address/model/clubbudget/TotalBudget.java
  src/test/java/seedu/address/logic/commands/BudgetCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/BudgetCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/BudgetCalculationCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ViewClubBudgetsCommandParserTest.java
  src/test/java/seedu/address/model/budgetelements/ClubBudgetElementsTest.java
  src/test/java/seedu/address/model/budgetelements/UniqueClubsListTest.java
  src/test/java/seedu/address/model/clubbudget/FinalClubBudgetTest.java
  src/test/java/seedu/address/model/clubbudget/TotalBudgetTest.java
  src/test/java/seedu/address/model/clubbudget/UniqueClubBudgetListTest.java
  src/test/java/seedu/address/testutil/TypicalClubBudgetElements.java
Labels: type.task

#127 Sort command
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/logic/parser/SortingParams.java
  src/main/java/seedu/address/model/person/Parameter.java
  src/main/java/seedu/address/model/person/Person.java
Labels: priority.high, type.enhancement, type.epic

#130 Beautifying my code :)
  src/main/java/seedu/address/logic/commands/ExcludeNameFindCommand.java
  src/main/java/seedu/address/logic/commands/ExcludeTagFindCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/IncludeNameFindCommand.java
  src/main/java/seedu/address/logic/commands/IncludeTagFindCommand.java
  src/main/java/seedu/address/logic/commands/UndoFindCommand.java
  src/main/java/seedu/address/logic/commands/formatter/KeywordsOutputFormatter.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/TagContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/searchhistory/KeywordsRecord.java
  src/main/java/seedu/address/model/searchhistory/ReadOnlyKeywordsRecord.java
  src/main/java/seedu/address/model/searchhistory/SearchHistoryManager.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: priority.high

#126 Updated DG, UG, PPP, added more test, removed unnecessary adoc files and added logging and assertions
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/UserGuide_BACKUP_13948.adoc
  docs/UserGuide_BASE_13948.adoc
  docs/UserGuide_LOCAL_13948.adoc
  docs/UserGuide_REMOTE_13948.adoc
  docs/images/CorrectIdPasswordRole.PNG
  docs/images/CreateAccountFailure.PNG
  docs/images/InitialLoginBookList.PNG
  docs/images/LoginExtendedActivityDiagram.png
  docs/images/LoginSuccess.PNG
  docs/images/MissingLoginInput.PNG
  docs/images/RepeatLoginSequenceDiagram.png
  docs/images/WrongIdPasswordRole.PNG
  docs/team/chocological.adoc
  login/loginbook.xml
  src/main/java/seedu/address/logic/commands/CreateAccountCommand.java
  src/main/java/seedu/address/logic/commands/LoginCommand.java
  src/main/java/seedu/address/logic/commands/LoginUserIdPasswordRoleCommand.java
  src/main/java/seedu/address/logic/parser/LoginUserIdPasswordRoleCommandParser.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/commands/LoginUserIdPasswordRoleCommandTest.java
Labels: priority.high

#134 Reducing code duplication in find commands
  src/main/java/seedu/address/logic/commands/ExcludeNameFindCommand.java
  src/main/java/seedu/address/logic/commands/ExcludeTagFindCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/IncludeNameFindCommand.java
  src/main/java/seedu/address/logic/commands/IncludeTagFindCommand.java
  src/main/java/seedu/address/logic/commands/UndoFindCommand.java
Labels: priority.high

#136 Standardized UML diagrams and updated PPP
  docs/UserGuide.adoc
  docs/diagrams/LoginActivityDiagram.pptx
  docs/diagrams/LoginExtendedActivityDiagram.pptx
  docs/diagrams/LoginSequenceDiagram.pptx
  docs/diagrams/RepeatLoginSequenceDiagram.pptx
  docs/images/LoginActivityDiagram.png
  docs/images/LoginExtendedActivityDiagram.png
  docs/images/LoginSequenceDiagram.png
  docs/images/RepeatLoginSequenceDiagram.png
  docs/team/chocological.adoc
Labels: priority.high

#137 edited the view budgets command to display the budget as a floating point number with 2 sf
  README.adoc
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/BudgetCalculationCommandSequenceDiagram.pptx
  docs/diagrams/BudgetCommandSequenceDiagram.pptx
  docs/diagrams/ViewClubBudgetsCommandSequenceDiagram.pptx
  docs/images/BudgetCalculationCommandSequenceDiagram.png
  docs/images/BudgetCommandSequenceDiagram.png
  docs/images/ViewClubBudgetsCommandSequenceDiagram.png
  src/main/java/seedu/address/logic/BudgetCalculationManager.java
  src/main/java/seedu/address/logic/arithmetic/TotalAttendees.java
  src/main/java/seedu/address/logic/commands/BudgetCalculationCommand.java
  src/main/java/seedu/address/logic/commands/ViewClubBudgetsCommand.java
  src/main/java/seedu/address/model/clubbudget/FinalClubBudget.java
  src/main/java/seedu/address/model/clubbudget/TotalBudget.java
  src/main/java/seedu/address/storage/XmlAdaptedFinalClubBudget.java
  src/test/java/seedu/address/storage/XmlAdaptedFinalClubBudgetTest.java
  src/test/java/seedu/address/testutil/ClubBudgetElementsBookBuilder.java
  src/test/java/seedu/address/testutil/FinalClubBudgetBuilder.java
Labels: type.task

#139 Updated Non-functional requirements and appendix H of dev guide
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: priority.high

#140 V1.4documentations
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/SearchPruningSequenceDiagram.pptx
  docs/diagrams/SearchPruningStateDiagram.pptx
  docs/diagrams/UndoFindSequenceDiagram.pptx
  docs/diagrams/UndoSearchSequenceDiagram.pptx
  docs/images/SearchPruning2nd.png
  docs/images/SearchPruning4th.png
  docs/images/SearchPruning5th.png
  docs/images/SearchPruning7th.png
  docs/images/SearchPruning8th.png
  docs/images/SearchPruning9th.png
  docs/images/SearchPruningSequenceDiagram.png
  docs/images/UndoFindSequenceDiagram.png
  docs/images/clearSearchHistoryStack.png
  docs/images/executeNewSearchEmptyStack.png
  docs/images/executeNewSearchNonEmptyStack.png
  docs/images/undoSearchSequenceDiagram.png
  docs/team/ladderinc.adoc
Labels: priority.high

#144 more V1.4documentations
  README.adoc
  docs/DeveloperGuide.adoc
  docs/diagrams/ModelComponentClassBetterOopDiagram.pptx
  docs/diagrams/ModelComponentClassDiagram.pptx
  docs/diagrams/SearchPruningSequenceDiagram.pptx
  docs/diagrams/UndoFindSequenceDiagram.pptx
  docs/images/ModelClassDiagram.png
  docs/images/SearchPruningSequenceDiagram.png
  docs/images/Ui.png
  docs/images/UndoFindSequenceDiagram.png
  docs/team/ladderinc.adoc
Labels: priority.high

#145 Updated manual testing section of DG and login sequence diagram
  docs/DeveloperGuide.adoc
  docs/diagrams/LoginSequenceDiagram.pptx
  docs/images/LoginSequenceDiagram.png
Labels: priority.high

#155 Updated login sequence diagram to fit PPP 10 page limit
  docs/diagrams/RepeatLoginSequenceDiagram.pptx
  docs/images/RepeatLoginSequenceDiagram.png
Labels: priority.high
